INSERT INTO EMP(EMPNO,ENAME,JOB,SALARY,DEPTNO)
VALUES(7369,'SMITH','CLERK',800,20);
SELECT*FROM EMP


UPDATE EMP
SET job='CLERK'WHERE job='NULL';

ALTER TABLE EMP
ADD COLUMN date_join varchar(50);
SELECT * FROM EMP;
UPDATE EMP 
SET date_join='17-DEC-80' WHERE empno='7369';
SELECT * FROM EMP;
UPDATE EMP 
SET date_join='20-FEB-81' WHERE empno='7499';
UPDATE EMP 
SET date_join='22-FEB-81' WHERE empno='7521';
UPDATE EMP 
SET date_join='02-APR-81' WHERE empno='7566';
UPDATE EMP 
SET date_join='28-SEP-81' WHERE empno='7654';
UPDATE EMP 
SET date_join='01-MAY-81' WHERE empno='7698';
UPDATE EMP 
SET date_join='09-JUN-81' WHERE empno='7782';
UPDATE EMP 
SET date_join='19-APR-87' WHERE empno='7788';
UPDATE EMP 
SET date_join='17-NOV-81' WHERE empno='7839';
UPDATE EMP 
SET date_join='08-SEP-81' WHERE empno='7844';
UPDATE EMP 
SET date_join='23-MAY-87' WHERE empno='7876';
UPDATE EMP 
SET date_join='03-DEC-81' WHERE empno='7900';
UPDATE EMP 
SET date_join='03-DEC-81' WHERE empno='7902';
UPDATE EMP 
SET date_join='23-JAN-82' WHERE empno='7934';
SELECT DISTINCT job FROM EMP;
SELECT ename,deptno FROM EMP WHERE deptno IN(20,30);
SELECT ENAME, SALARY*12 AS ANNUAL_SALARY FROM EMP;
SELECT  (salary + IFNULL( commission,0)) AS total_salary FROM EMP WHERE ename='MILLER';
DELETE FROM EMP WHERE ename='MILLER';
SELECT ename,deptno FROM EMP;
ALTER TABLE EMP ADD COLUMN total_salary numeric;
UPDATE EMP SET total_salary=(salary+IFNULL(COMMISSION,0));
ALTER TABLE EMP DROP COLUMN commission;
SELECT ename AS name,empno AS emp_id  FROM EMP;
RENAME TABLE EMP to EMPLOYEE;
DESCRIBE EMPLOYEE;
CREATE TABLE EMPTABLE AS SELECT*FROM EMPLOYEE;
DESCRIBE EMPLOYEE;
SELECT *FROM EMPTABLE;

